### ISSUE TITLE
Provide database fixtures

### ISSUE THREAD

**Issue by malisetti** [lightfactor/lightfactor-engine#1]
Is it possible to have the sample database.

**Comment by jcesnik** [comment]
Yes - we're working on it...  stay tuned.

**Comment by notrehtad** [comment]
I will push an update that _will_ include this early next week. It _will_ also include additional scripts to generate SSL CA and cert for local execution. It _may_ coincide with a docker image release.

**Comment by notrehtad** [comment]
A script to insert bootstrapping objects (which are provided for review) and create indexes was pushed in the latest release... as was the SSL generation script and its output.
