### ISSUE TITLE
UAF Registration Response API : Error

### ISSUE THREAD

**Issue by maheswaranapk** [lightfactor/lightfactor-engine#4]
I am trying to build Android UAF Client using LightFactor Server.

When I calling Post --> **https://*.ngrok.io/Send/Reg**

with Below JSON Body Data:
{"uafResponse":"[{\"assertions\":[{\"assertion\":\"AT...AuMKvuE1J73jp4\",\"assertionScheme\":\"UAFV1TLV\"}],\"fcParams\":\"eyJhcHBJ..2V0SUQiOiIifQ\",\"header\":{\"appID\":\"https://*.ngrok.io/\",\"op\":\"Reg\",\"serverData\":\"VVVxGF0igHWYCW9rl_pm2sMVI25EFfXxO7qptrjMP9I\",\"upv\":{\"major\":1,\"minor\":0}}}]"}

I am getting below **Response** 
{
  "statusCode": 1498,
  "message": "Schema validation failed",
  "field": ".facetID",
  "info": "should NOT be shorter than 1 characters"
}

When after adding "facetID" in uafResponse JSON stringify version, Still I am getting this issue.

**Comment by jcesnik** [comment]
The appID you specified in your request is invalid - it must be a fully qualified domain name, no wildcards allowed.

 

To support more than one unique host, you must use the TrustedFacets mechanism.  Please refer to the FIDO AppID and Facet Specification available at fidoalliance.org.
